apiVersion: v1
kind: Pod
metadata:
  name: nginx-lb
  namespace: haproxy-demo
  annotations:
    k8s.v1.cni.cncf.io/networks: |-
      [
        {
          "name": "demo-21",
          "namespace": "haproxy-demo",
          "default-route": ["192.168.21.1"]
        }
      ]
spec:
  containers:
  - name: nginx-lb
    image: quay.io/ashisha/nginx-lb
    volumeMounts:
    - name: "config-volume"
      mountPath: "/etc/nginx/conf.d/default.conf"
      subPath: "default.conf"
  volumes:
  - name: "config-volume"
    configMap:
      name: "nginx-conf"
    restartPolicy: Never      
